# The publication date of this version. Must follow the RFC 3339 date format.
time = "2024-11-14T04:53:40.323012500+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
