# The publication date of this version. Must follow the RFC 3339 date format.
time = "2025-05-28T16:10:35.578265100+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
