# The publication date of this version. Must follow the RFC 3339 date format.
time = "2024-11-11T16:36:54.447634+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
