# The publication date of this version. Must follow the RFC 3339 date format.
time = "2024-07-18T04:19:55.494372600+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
