# The publication date of this version. Must follow the RFC 3339 date format.
time = "2025-05-29T16:41:46.472427600+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
