# The publication date of this version. Must follow the RFC 3339 date format.
time = "2025-06-23T16:28:04.707283500+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
