# The publication date of this version. Must follow the RFC 3339 date format.
time = "2024-09-07T19:17:17.818440700+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["My other script.lua"]
