# The publication date of this version. Must follow the RFC 3339 date format.
time = "2024-09-07T18:47:51.982597100+00:00"

# # Optional: Override entrypoints defined in the package configuration.
# [entrypoints]
# main = ["Detect (Highlight) Offset Items.lua"]
