name: Create index

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Install reapack-indexer-4
        run: cargo install --git https://github.com/jamesWalker55/reapack-indexer-4

      - name: Generate index
        run: reapack-indexer-4 export --repo . index.xml

      - name: Commit changes and push to a new branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          skip_checkout: true
          skip_fetch: true
          create_branch: true
          branch: main-index
          file_pattern: 'index.xml'
          add_options:  --force
          commit_message: (GitHub Actions) Generate index
          commit_options: --signoff
          push_options: --force
          skip_dirty_check: true
